spring:
  application:
    name: demo-spring-webflux
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      schema-locations: schema.sql
      mode: embedded
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: sa
  data:
    r2dbc:
      repositories:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: none
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console
logging:
  level:
    root: info