spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sfidencio/study-on-good-practices.git
        bootstrap: true
server:
  port: 8888
